"""Add field product_shopping_cart_id into shopping_cart

Revision ID: 2a586ffb7aa0
Revises: 9469a3eb3255
Create Date: 2025-05-26 16:03:00.488108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a586ffb7aa0'
down_revision: Union[str, None] = '9469a3eb3255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('product_shopping_cart_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shopping_cart', 'product_shopping_cart', ['product_shopping_cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_cart', type_='foreignkey')
    op.drop_column('shopping_cart', 'product_shopping_cart_id')
    # ### end Alembic commands ###
