"""Remove field user_id from shopping_cart

Revision ID: 7529027772b3
Revises: 2a586ffb7aa0
Create Date: 2025-05-26 16:11:51.244128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7529027772b3'
down_revision: Union[str, None] = '2a586ffb7aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shopping_cart_user_id_key'), 'shopping_cart', type_='unique')
    op.drop_column('shopping_cart', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('shopping_cart_user_id_key'), 'shopping_cart', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
